### ISSUE TITLE
Suggestion: Add convenience import

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/vaadin-lumo-styles#13]
In a majority of cases, users will want to include all the following parts of Lumo. Could we add a combined import that pulls in all of them? Document the pros/cons of using the convenience import and retain the ability to import individual parts. 

```
<link rel="import" href="bower_components/vaadin-lumo-styles/color.html">
<link rel="import" href="bower_components/vaadin-lumo-styles/sizing.html">
<link rel="import" href="bower_components/vaadin-lumo-styles/spacing.html">
<link rel="import" href="bower_components/vaadin-lumo-styles/style.html">
<link rel="import" href="bower_components/vaadin-lumo-styles/typography.html">
```

**Comment by jouni** [comment]
This has actually been fixed a while ago in #60 

Not documented, though.
