### ISSUE TITLE
vaadin lumo theme for especific components

### ISSUE THREAD

**Issue by elgomy** [vaadin/vaadin-lumo-styles#16]
As valo-theme had default theme (with some styles applied)  for especific components like vaadin-combo-box I can't find something similar in vaadin-lumo-styles....am I missing something? thanks!!

**Comment by web-padawan** [comment]
Starting from the latest major versions, the components use Lumo theme by default, and the theme files have been moved to the correspondent repos. See file structure docs for combo-box [here](https://github.com/vaadin/vaadin-combo-box#the-file-structure-for-vaadin-components).
