### ISSUE TITLE
Custom properties docs missing entries

### ISSUE THREAD

**Issue by robrez** [vaadin/vaadin-lumo-styles#21]
I noticed that [this page](https://cdn.vaadin.com/vaadin-lumo-styles/1.0.0-beta3/demo/colors.html#custom-properties) is missing the '10pct' values for shade, tint and contrast

Not sure if this is the right place to report issues related to documentation

**Comment by jouni** [comment]
Oh, indeed. Absolutely the correct place – thanks!
