### ISSUE TITLE
After 'Add a “kitchen sink” example' master does not build for Polymer 3

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-lumo-styles#27]
Try convert master with `magi` then run `yarn install` and it fails due to a new dependency of `@vaadin/elements-demo-resources` which actually does not exist

**Comment by jouni** [comment]
Is this issue still relevant? Should we keep it open?

**Comment by web-padawan** [comment]
I don't think we want to convert kitchen sink to Polymer 3 for now. Closing.
