### ISSUE TITLE
It should be easy to define the mouse cursor for buttons and other actionable items

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-lumo-styles#37]
Currently, Lumo does not use `pointer: cursor;` for many of the clickable items in the UI (buttons, dropdown toggles, checkboxes/radio buttons, list items). This is a deliberate choice, that the pointer cursor is reserved for “link-like” actions. Tabs is currently an exception, as they are not actual links, though they are a similar navigational element as traditional links.

But, this is a divisive topic (see [this](https://adamsilver.io/articles/buttons-shouldnt-have-a-hand-cursor-part-2/) and [this article](https://medium.com/@thepascalheynol/on-the-web-maybe-buttons-should-have-a-hand-cursor-1e4498c42b3e) and [this discussion](https://www.designernews.co/stories/71835-buttons-shouldnt-have-a-hand-cursor)), and we should make it easy to switch to the opposite “camp” where most clickable elements do have `pointer: cursor;`.

Something like a `--lumo-clickable-cursor` property which could be used in the component themes.

**Comment by mlopezFC** [comment]
Hi, in the description of the issue, Jouni mentioned _for many of the clickable items in the UI (buttons, dropdown toggles, checkboxes/radio buttons, list items)._ but then for what I was able to see [this was only applied to buttons](https://github.com/vaadin/vaadin-lumo-styles/pull/56/commits/4aa443eaca72b7d2f7f360e7fce639f81652fcf7), not to other clickable elements like checkboxes and radio groups.

**Comment by jouni** [comment]
Yes, the change is still yet to be done for most of the components. We should open issue for each individual component to track that we apply this property there.
