### ISSUE TITLE
The overlay doesn't fit the window

### ISSUE THREAD

**Issue by Bodhiz** [vaadin/vaadin-lumo-styles#48]
The overlay doesn't fit correctly the entire window as shown on the following screenshot :

![image](https://user-images.githubusercontent.com/2632229/47364494-bc49ca80-d6d9-11e8-966c-94842ce98950.png)

**Comment by web-padawan** [comment]
Thanks for the issue. The change caused the regression was reverted in 2ce5a6d and released as 1.3.1
