### ISSUE TITLE
Dark Variant - Shadows are too light

### ISSUE THREAD

**Issue by appreciated** [vaadin/vaadin-lumo-styles#51]
### Description:
When using the `Dark` variant of the Lumo Theme the shadow is rather invisible (at least on my monitor 😅) when showing content with a `--lumo-box-shadow...` on the default background-color, the content is visually hard to seperate from the background. 

### A clearly visible shadow in the Light Theme:
![example-light](https://user-images.githubusercontent.com/1729845/48015654-ec598a80-e129-11e8-8df9-0d171e518060.PNG)

### A seemingly invisible shadow in the Dark Theme:
![example-dark-no-shadow](https://user-images.githubusercontent.com/1729845/48015663-efed1180-e129-11e8-99ca-eb6f18d91a9b.PNG)

In Lumo terms speaking the default contrast between `--lumo-base-color` and the resulting:
- `--lumo-box-shadow-s`   
- `--lumo-box-shadow-m` 
- `--lumo-box-shadow-l`
- `--lumo-box-shadow-xl`

is (in my opinion) too small. 

The low contrast may cause "floating elements" to appear "non floating" and could be disturbing in some cases when using non-modal dialoges or any components that make use of context menus. 

As a fix I suggest to make the shadows in the Dark theme even darker. 

### A visible shadow in the Lumo Dark Theme:
![example-dark-shadow](https://user-images.githubusercontent.com/1729845/48015717-127f2a80-e12a-11e8-8e45-e32b45c62e9c.PNG)

The used css:
```
--lumo-box-shadow-s: 0 1px 2px 0 var(--lumo-shade-80pct), 0 2px 8px -2px var(--lumo-shade);
--lumo-box-shadow-m: 0 2px 6px -1px var(--lumo-shade-80pct), 0 8px 24px -4px var(--lumo-shade);
--lumo-box-shadow-l: 0 3px 18px -2px var(--lumo-shade-80pct), 0 12px 48px -6px var(--lumo-shade);
--lumo-box-shadow-xl: 0 4px 24px -3px var(--lumo-shade-80pct), 0 18px 64px -8px var(--lumo-shade);
```

**Comment by jouni** [comment]
Here’s what I got when I used `<html theme="dark">` in https://cdn.vaadin.com/vaadin-lumo-styles/1.3.3/test/sink.html on Chrome/macOS.

<img width="322" alt="screen shot 2018-11-06 at 9 35 38" src="https://user-images.githubusercontent.com/66382/48049447-6714bb00-e1a7-11e8-83d8-904fcf4b8179.png">

It’s a little more visible than in your first screenshot. What browser did you use to take the screenshots? I think this could be affected by that as well.

You can easily see the shadows and compare the light vs dark palettes here: https://cdn.vaadin.com/vaadin-lumo-styles/1.3.3/demo/styles.html

**Comment by appreciated** [comment]
### System Information
**OS:** Windows 10 
**Vaadin Flow Version:** 11
**Browsers:** Looks the same on any browser I got installed (Chrome, Chromium and FF)

The Flow Project was created by simply using the [project-base](https://vaadin.com/start/latest/project-base). 

> Here’s what I got when I used <html theme="dark"> in https://cdn.vaadin.com/vaadin-lumo-styles/1.3.3/test/sink.html on Chrome/macOS.

The dark theme in the `vaadin-lumo-styles` example project of yours looks way better! 
### Side by Side 
![side-by-side](https://user-images.githubusercontent.com/1729845/48079876-9dc0f480-e1ec-11e8-9e53-0b0590848aed.PNG)

The problem doesn't to occur in your example project, so maybe a dependeny layer above?
As I can see the color values for the shadows are different to my example Application.

### Side by Side CSS Values
![side-by-side-values](https://user-images.githubusercontent.com/1729845/48079916-b6c9a580-e1ec-11e8-8215-e0e321cd1483.PNG)

As being said I used the `project-base` and added only a ComboBox here the Example Code:
```
@Route("")
@Theme(value = Lumo.class, variant = Lumo.DARK)
public class MainView extends VerticalLayout {

    public MainView() {
        Button button = new Button("Click me", event -> Notification.show("Clicked!"));
        ComboBox<String> box = new ComboBox<>("Test", Arrays.asList(new String[]{"Abcdefg", "Abcdefg", "Abcdefg"}));
        add(button, box);
        box.setOpened(true);
    }
}
```

Since this issue does not seem to be related to this project in particular, should I post this issue in the flow project then?

**Comment by jouni** [comment]
Thanks for the investigation 🙇 

Yeah, it seems that the way CSS custom properties are evaluated is causing the problem. The `--lumo-box-shadow-*` properties are evaluated in the scope of the `html` tag, and the reassingment of the Lumo color properties then in the scope of `body` does not force them to be re-evaluated in that scope.

One solution is to use the universal `*` selector for the box-shadow properties instead of the `html` selector. Not really sure what kind of side-effects that would have…

**Comment by jouni** [comment]
I’m closing this in favor of https://github.com/vaadin/flow/issues/4765
