### ISSUE TITLE
Don't encourage to add styles to index.html

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-lumo-styles#6]
https://github.com/vaadin/vaadin-lumo-styles/blob/master/demo/index.html#L48 <--

Let's say you are using [Polymer Starter Kit](https://github.com/PolymerElements/polymer-starter-kit) and when building a bundled version of your project, it will not bundle the imports in index.html. Now you could add these as extra dependencies in [polymer.json](https://github.com/PolymerElements/polymer-starter-kit/blob/master/polymer.json#L14), but then you'll be importing Polymer from two sources and bundled app will break.

I'd solve this issue by creating a style module (where lumo is imported) and use it in all of my elements but not sure which is the best solution.

**Comment by jouni** [comment]
Thanks for the suggestion! I don’t have any experience in creating a production-ready Polymer app or bundling, so I appreciate all the help.

**Comment by web-padawan** [comment]
We could suggest adding those imports to the app shell, which is intended to be the only file imported by `index.html`, so the styles could be "global". 

Shared style module is nice as well.

**Comment by web-padawan** [comment]
The new documentation site which is currently WIP will not mention HTML imports and `index.html`. Closing.
