### ISSUE TITLE
Dark palette should be a similar preset as compact

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-lumo-styles#62]
Currently, the dark palette is always loaded for all apps even if it is not used.

We should refactor the dark palette into a similar preset as the new [compact preset](https://github.com/vaadin/vaadin-lumo-styles/blob/master/presets/compact.html). That would fix #50.

But, it will also remove the feature of using the `theme="dark"` attribute on the HTML element (or any other element), so it’s a breaking change. Therefore it seems like it should be postponed until Lumo 2.0.

**Comment by anezthes** [comment]
Not a fan. Being able to switch between light and dark with a single attribute is an amazing feature IMO. If you do this, please make sure there's a just-as-easy-to-use replacement.

**Comment by jouni** [comment]
@anezthes, yeah, that use case can be reconsidered after Vaadin 14, as we no longer need to think about IE11 support. So custom properties will work without ShadyCSS limitations.

To clarify, this issue is more about unifying the concepts of dark and compact, so that they work the same way. So what you said about the dark palette applies to the compact preset as well – sometimes it is great to apply that to a subset of the page.

**Comment by jouni** [comment]
Closing in favor of #69
