### ISSUE TITLE
Font-icon generation is broken in "gulp icons" task

### ISSUE THREAD

**Issue by Haprog** [vaadin/vaadin-lumo-styles#66]
Currently if I run `gulp icons` (in `master` branch) the generated `font-icons.html` seems to have some differences to the committed one, and after that when looking at the demos locally, the spacing of the font icons seems to be broken.

This is how the font icon demos look like after running `gulp icons`:

![image](https://user-images.githubusercontent.com/75155/54455899-84fdb800-4765-11e9-896e-bb9cb3f00e8e.png)
![image](https://user-images.githubusercontent.com/75155/54455928-92b33d80-4765-11e9-8653-99441c27b0e4.png)

This is how they looked before:

![image](https://user-images.githubusercontent.com/75155/54456004-bfffeb80-4765-11e9-8d0e-53b8e37e88b1.png)
![image](https://user-images.githubusercontent.com/75155/54456016-c8f0bd00-4765-11e9-9a12-c8ec02e8ac76.png)

**Comment by Haprog** [comment]
I'm not sure if this also affects [vaadin-material-styles](https://github.com/vaadin/vaadin-material-styles) which has a `material-icons` font icon generated via similar gulp task. Material theme doesn't have a similar Icons demo (in there icons are only used as parts of the component themes, e.g. calendar icon in date picker or eye icon in password field). At least there also running `gulp icons` will currently generate a font (in `font-icons.html`) which is not identical to the committed one.

**Comment by web-padawan** [comment]
This should be fixed by #88, and there is a PR for Material at https://github.com/vaadin/vaadin-material-styles/pull/98. Closing.
