### ISSUE TITLE
Dead elements-demo-resources dependency

### ISSUE THREAD

**Issue by smashah** [vaadin/vaadin-lumo-styles#68]
When going into the node_modules vaadin-lumo-styles directory and doing npm install, I get this error:

`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vaadin%2felements-demo-resources - Not found
npm ERR! 404 
npm ERR! 404  '@vaadin/elements-demo-resources@^2.1.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@vaadin/vaadin-lumo-styles'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url`

going in and deleting this dependency from package.json fixes the issue. What is the purpose for this dependency?

**Comment by jouni** [comment]
You are not supposed to run `npm install` in the vaadin-lumo-style package folder after you’ve installed the package from npm. 

The npm package is converted automatically during release from the Bower-based package (them implementation which is in the master branch). The Bower-based implementation depends on the elements-demo-resources which is available in [GitHub](https://github.com/vaadin/elements-demo-resources) (as Bower uses GitHub as its primary repo).

The purpose of that dependency is to provide all the needed things for the documentation of the package, i.e. https://vaadin.com/themes/lumo

Both of these will be going away eventually. The Bower package will be discontinued and the documentation will be moved elsewhere.
